// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQBBO5nmW7a62CvDkSLrqOHmMjXP_RYo',
    appId: '1:554666140805:web:8b24d5751a3000c99275ec',
    messagingSenderId: '554666140805',
    projectId: 'ap55-flutter-project',
    authDomain: 'ap55-flutter-project.firebaseapp.com',
    storageBucket: 'ap55-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0KTUBf4rIUpXInYnqkgGahmJS63Blo4',
    appId: '1:554666140805:android:97e1ff0821e25d209275ec',
    messagingSenderId: '554666140805',
    projectId: 'ap55-flutter-project',
    storageBucket: 'ap55-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSUydjkQHwXzh3T722ILuKEcPrWG_jXc',
    appId: '1:554666140805:ios:7495f734a7cd9e449275ec',
    messagingSenderId: '554666140805',
    projectId: 'ap55-flutter-project',
    storageBucket: 'ap55-flutter-project.appspot.com',
    iosClientId: '554666140805-7on1nspofeqcr27toss1pj7ckmjf0hut.apps.googleusercontent.com',
    iosBundleId: 'com.example.app55',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSUydjkQHwXzh3T722ILuKEcPrWG_jXc',
    appId: '1:554666140805:ios:7495f734a7cd9e449275ec',
    messagingSenderId: '554666140805',
    projectId: 'ap55-flutter-project',
    storageBucket: 'ap55-flutter-project.appspot.com',
    iosClientId: '554666140805-7on1nspofeqcr27toss1pj7ckmjf0hut.apps.googleusercontent.com',
    iosBundleId: 'com.example.app55',
  );
}
